"$schema" = "./node_modules/wrangler/config-schema.json"

name = "searchgal"
main = "src/index.ts"
compatibility_date = "2026-05-27"

[observability.logs]
enabled = true

[vars]
ENVIRONMENT = "production"

# KV 缓存
[[kv_namespaces]]
binding = "SEARCHGAL_KV"
id = "d547b4afb56146a09d29365560eaf530"
# 如需预览环境使用不同 KV，取消注释下方并创建预览命名空间
# preview_id = "你的预览环境_KV_ID"
